[package]
name = "generate_keys"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ethers = "2.0"
hex = "0.4.3"
near-crypto = "0.27"
mpc-keys = { path = "../../../chain-signatures/keys" }
rand = "0.8"