apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: secrets-init
  namespace: default
spec:
  interval: 10m
  chart:
    spec:
      chart: kube-secrets-init
      version: '0.9.3'
      sourceRef:
        kind: HelmRepository
        name: secrets-init
        namespace: flux-system
      interval: 10m
  values:
    replicaCount: 3
    provider: google
    namespaceSelector:
      matchExpressions:
        - key: name
          operator: NotIn
          values:
            - kube-system
            - gmp-system