apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: multichain-ingress
  annotations:
    kubernetes.io/ingress.global-static-ip-name: multichain-mainnet-0
    networking.gke.io/managed-certificates: managed-cert
    kubernetes.io/ingress.class: "gce"
spec:
  defaultBackend:
    service:
      name: multichain-mainnet-0
      port:
        number: 3000